#!/bin/python

WORKS = """
2 KING HENRY VI
3 KING HENRY VI
1 KING HENRY VI
KING RICHARD III
VENUS AND ADONIS
THE RAPE OF LUCRECE
KING RICHARD II
KING JOHN
1 KING HENRY IV
2 KING HENRY IV
KING HENRY V
SONNETS
A LOVER'S COMPLAINT
THE PASSIONATE PILGRIM
SONNETS TO SUNDRY NOTES OF MUSIC
LOVE'S ANSWER.
THE PHOENIX AND THE TURTLE
KING HENRY VIII
THE TWO GENTLEMEN OF VERONA
THE TAMING OF THE SHREW
THE COMEDY OF ERRORS
LOVE'S LABOUR'S LOST
A MIDSUMMER NIGHT'S DREAM
THE MERCHANT OF VENICE
THE MERRY WIVES OF WINDSOR
MUCH ADO ABOUT NOTHING
AS YOU LIKE IT
TWELFTH NIGHT
TROILUS AND CRESSIDA
MEASURE FOR MEASURE
ALL'S WELL THAT ENDS WELL
PERICLES, PRINCE OF TYRE
THE WINTER'S TALE
CYMBELINE
THE TEMPEST
TITUS ANDRONICUS
ROMEO AND JULIET
JULIUS CAESAR
HAMLET
OTHELLO
TIMON OF ATHENS
KING LEAR
MACBETH
ANTONY AND CLEOPATRA
CORIOLANUS
GLOSSARY
""".split('\n')[1:-1]

PLAYS = """
2 KING HENRY VI
3 KING HENRY VI
1 KING HENRY VI
KING RICHARD III
KING RICHARD II
KING JOHN
1 KING HENRY IV
2 KING HENRY IV
KING HENRY V
KING HENRY VIII
THE TWO GENTLEMEN OF VERONA
THE TAMING OF THE SHREW
THE COMEDY OF ERRORS
LOVE'S LABOUR'S LOST
A MIDSUMMER NIGHT'S DREAM
THE MERCHANT OF VENICE
THE MERRY WIVES OF WINDSOR
MUCH ADO ABOUT NOTHING
AS YOU LIKE IT
TWELFTH NIGHT
TROILUS AND CRESSIDA
MEASURE FOR MEASURE
ALL'S WELL THAT ENDS WELL
PERICLES, PRINCE OF TYRE
THE WINTER'S TALE
CYMBELINE
THE TEMPEST
TITUS ANDRONICUS
ROMEO AND JULIET
JULIUS CAESAR
HAMLET
OTHELLO
TIMON OF ATHENS
KING LEAR
MACBETH
ANTONY AND CLEOPATRA
CORIOLANUS
""".split('\n')[1:-1]

POEMS = """
SONNETS
A LOVER'S COMPLAINT
THE PASSIONATE PILGRIM
SONNETS TO SUNDRY NOTES OF MUSIC
LOVE'S ANSWER.
THE PHOENIX AND THE TURTLE
THE RAPE OF LUCRECE
VENUS AND ADONIS
""".split('\n')[1:-1]

def simple_name(work):
    import re
    return re.sub(r'\W+', '', work.lower().replace(' ', '_'))

def noncap_name(work):

    replacements = {
            "1 KING HENRY VI": "King Henry VI - Part 1",
            "2 KING HENRY VI": "King Henry VI - Part 2",
            "3 KING HENRY VI": "King Henry VI - Part 3",
            "1 KING HENRY IV": "King Henry IV - Part 1",
            "2 KING HENRY IV": "King Henry IV - Part 2",
    }

    if work in replacements:
        return replacements[work]

    title = ' '.join([word.capitalize() for word in work.split(' ')])
    title = title.replace('Viii', 'VIII')
    title = title.replace('Vi', 'VI')
    title = title.replace('Iv', 'IV')
    title = title.replace('Iii', 'III')
    title = title.replace('Ii', 'II')
    return title

